import{a as q,S as E,i as n}from"./assets/vendor-BkC4bTqC.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const I="55026716-4dbe0fcfc8dcb0cc6e29137c8",R="https://pixabay.com/api/";async function m(r,t=1){try{return(await q.get(R,{params:{key:I,q:r,image_type:"photo",orientation:"horizontal",page:t,per_page:15,safesearch:!0,lang:"ru"}})).data}catch(i){throw console.error("Error fetching images:",i),i}}const g=document.querySelector(".gallery"),h=document.querySelector(".loader"),f=document.querySelector(".btn-more"),$=new E(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const t=r.map(({webformatURL:i,largeImageURL:l,tags:e,likes:o,views:s,comments:w,downloads:S})=>`
<li class="gallery-item">
  <a href="${l}">
    <img src="${i}" alt="${e}" />
    <div class="info">
      <p>Likes ${o}</p>
      <p>Views ${s}</p>
      <p>Comments ${w}</p>
      <p>Downloads ${S}</p>
    </div>
  </a>
</li>`).join("");g.insertAdjacentHTML("beforeend",t),$.refresh()}function B(){g.innerHTML=""}function L(){h.classList.add("visible")}function b(){h.classList.remove("visible")}function v(){f.classList.add("visible")}function a(){f.classList.remove("visible")}const p=document.querySelector(".form");let c=1,d="",u=0;p.addEventListener("submit",async r=>{if(r.preventDefault(),d=r.target.elements.search.value.trim(),!!d){c=1,B(),a(),L();try{const t=await m(d,c);if(u=t.totalHits,t.hits.length===0){n.warning({message:"Немає результатів для цього запиту",position:"topRight"});return}y(t.hits),t.hits.length<u?v():a()}catch{n.error({message:"Помилка запиту",position:"topRight"})}finally{b()}p.reset()}});f.addEventListener("click",async()=>{c+=1,L(),a();try{const r=await m(d,c);if(r.hits.length===0){a(),n.info({message:"Більше картинок немає",position:"topRight"});return}y(r.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),c*15<u?v():(a(),n.info({message:"Більше картинок немає",position:"topRight"}))}catch{n.error({message:"Помилка запиту",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
