import{a as q,S as R,i as n}from"./assets/vendor-BkC4bTqC.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const $="55026716-4dbe0fcfc8dcb0cc6e29137c8",E="https://pixabay.com/api/";async function m(r,t=1,i=15){i<15&&(i=15);try{return(await q.get(E,{params:{key:$,q:r,image_type:"photo",orientation:"horizontal",page:t,per_page:i,safesearch:!0,lang:"ru"}})).data}catch(s){throw console.error("Error fetching images:",s),s}}const g=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".btn-more");function y(){h.classList.add("visible")}function c(){h.classList.remove("visible")}const I=new R(".gallery a",{captionsData:"alt",captionDelay:250});function L(r){const t=r.map(({webformatURL:i,largeImageURL:s,tags:e,likes:o,views:a,comments:w,downloads:S})=>`
<li class="gallery-item">
  <a href="${s}">
    <img src="${i}" alt="${e}" />
    <div class="info">
      <p>Likes ${o}</p>
      <p>Views ${a}</p>
      <p>Comments ${w}</p>
      <p>Downloads ${S}</p>
    </div>
  </a>
</li>`).join("");g.insertAdjacentHTML("beforeend",t),I.refresh()}function M(){g.innerHTML=""}function b(){p.classList.add("visible")}function v(){p.classList.remove("visible")}const f=document.querySelector(".form"),B=document.querySelector(".btn-more");let d=1,l="",u=0;f.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements.search.value.trim(),!!l){d=1,M(),c(),b();try{const t=await m(l,d);if(u=t.totalHits,t.hits.length===0){n.warning({message:"Немає результатів для цього запиту",position:"topRight"});return}L(t.hits),t.hits.length<u?y():(c(),n.info({message:"Більше картинок немає",position:"topRight"}))}catch{n.error({message:"Помилка запиту",position:"topRight"})}finally{v()}f.reset()}});B.addEventListener("click",async()=>{d+=1,b(),c();try{const r=await m(l,d);if(r.hits.length===0){c(),n.info({message:"Більше картинок немає",position:"topRight"});return}L(r.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length<u?y():(c(),n.info({message:"Більше картинок немає",position:"topRight"}))}catch{n.error({message:"Помилка запиту",position:"topRight"})}finally{v()}});
//# sourceMappingURL=index.js.map
