import{a as S,S as q,i as n}from"./assets/vendor-BkC4bTqC.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const R="55026716-4dbe0fcfc8dcb0cc6e29137c8",E="https://pixabay.com/api/";async function f(r,t=1,s=15){try{return(await S.get(E,{params:{key:R,q:r,image_type:"photo",orientation:"horizontal",page:t,per_page:s,safesearch:!0,lang:"ru"}})).data}catch(i){throw console.error("Error fetching images:",i),i}}const p=document.querySelector(".gallery"),g=document.querySelector(".loader");function h(){document.querySelector(".btn-more").classList.add("visible")}function c(){document.querySelector(".btn-more").classList.remove("visible")}const I=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const t=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:a,comments:v,downloads:w})=>`
<li class="gallery-item">
  <a href="${i}">
    <img src="${s}" alt="${e}" />
    <div class="info">
      <p>Likes ${o}</p>
      <p>Views ${a}</p>
      <p>Comments ${v}</p>
      <p>Downloads ${w}</p>
    </div>
  </a>
</li>`).join("");p.insertAdjacentHTML("beforeend",t),I.refresh()}function $(){p.innerHTML=""}function L(){g.classList.add("visible")}function b(){g.classList.remove("visible")}const m=document.querySelector(".form"),B=document.querySelector(".btn-more");let d=1,l="",u=0;m.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements.search.value.trim(),!!l){d=1,$(),c(),L();try{const t=await f(l,d);if(u=t.totalHits,t.hits.length===0){n.warning({message:"Немає результатів для цього запиту",position:"topRight"});return}y(t.hits),t.hits.length<u?h():(c(),n.info({message:"Більше картинок немає",position:"topRight"}))}catch{n.error({message:"Помилка запиту",position:"topRight"})}finally{b()}m.reset()}});B.addEventListener("click",async()=>{d+=1,L(),c();try{const r=await f(l,d);if(r.hits.length===0){c(),n.info({message:"Більше картинок немає",position:"topRight"});return}y(r.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length<u?h():(c(),n.info({message:"Більше картинок немає",position:"topRight"}))}catch{n.error({message:"Помилка запиту",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
